[workspace]
members = [
    "./nestadia",
#    "./nestadia-gui", // Deprecated
    "./nestadia-server",
    "./nestadia-wasm",
    "./nestadia-wgpu",
]

[profile.dev]
# Slightly better optimizations.
opt-level = 1

[profile.release]
codegen-units = 1

